db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  name: "chat-bot"
  timeout: 5
  maxIdleConn: 5
  maxOpenConn: 5
http:
  address: "0.0.0.0:9031"
gemini:
  apikey: "fshfiojsdifjsidjgfgidsjgfidsjfi"